from __future__ import annotations

from dataclasses import dataclass
import hashlib
import os
from pathlib import Path
import subprocess

from .symbolic import Expr


ROOT = Path(__file__).resolve().parents[1]
BEND_ROOT = Path(os.environ.get("BEND_ROOT", ROOT.parent / "bend"))
BEND = BEND_ROOT / "bend2/main.ts"
CACHE = ROOT / ".build/cache"


class BackendError(RuntimeError):
    pass


@dataclass(frozen=True)
class Domain:
    start: int
    end: int

    @property
    def size(self) -> int:
        return self.end - self.start + 1


def balanced_search(predicates: tuple[Expr, ...], domains: tuple[Domain, ...], candidates: int, backend: str, threads: int = 0, gpu_memory: str = "1GB") -> int | None:
    if candidates < 0 or candidates > 2**32 - 1:
        raise ValueError("candidate count must fit U32")
    if backend not in {"cpu", "gpu"}:
        raise ValueError("backend must be cpu or gpu")
    if backend == "gpu" and gpu_memory.lower() == "off":
        raise ValueError("GPU memory cannot be 'off' for a GPU search")
    depth = 0
    leaves = 1
    while leaves < max(1, candidates):
        depth += 1
        leaves *= 2
    source = generate_source(predicates, domains, candidates, depth, backend == "gpu")
    digest = hashlib.sha256(source.encode()).hexdigest()[:20]
    CACHE.mkdir(parents=True, exist_ok=True)
    bend_file = CACHE / f"search-{digest}.bend"
    binary = CACHE / f"search-{digest}"
    if not binary.exists():
        bend_file.write_text(source, encoding="utf-8")
        result = subprocess.run(["bun", str(BEND), str(bend_file), "-o", str(binary)], cwd=ROOT, text=True, capture_output=True)
        if result.returncode != 0:
            raise BackendError(f"Bend compilation failed:\n{result.stderr or result.stdout}")
    command = [str(binary)]
    if backend == "gpu":
        command += ["--gpu", gpu_memory]
    else:
        command += ["--gpu", "off"]
        if threads > 0:
            command += ["--threads", str(threads)]
    result = subprocess.run(command, cwd=ROOT, text=True, capture_output=True)
    if result.returncode != 0:
        raise BackendError(f"Bend {backend} execution failed:\n{result.stderr or result.stdout}")
    output = result.stdout.strip()
    if output == "NONE":
        return None
    try:
        index = int(output)
    except ValueError as error:
        raise BackendError(f"unexpected Bend output: {output!r}") from error
    if index < 0 or index >= candidates:
        raise BackendError(f"Bend returned out-of-range candidate {index}")
    return index


def decode_candidate(index: int, domains: tuple[Domain, ...]) -> tuple[int, ...]:
    values = []
    for domain in domains:
        values.append(domain.start + index % domain.size)
        index //= domain.size
    return tuple(values)


def generate_source(predicates: tuple[Expr, ...], domains: tuple[Domain, ...], candidates: int, depth: int, use_gpu: bool = False) -> str:
    input_defs = []
    stride = 1
    for index, domain in enumerate(domains):
        if stride > 2**32 - 1:
            offset = "0"
        else:
            quotient = f"U32.div(idx, {stride})"
            offset = quotient if domain.size == 2**32 else f"U32.mod({quotient}, {domain.size})"
        input_defs.append(
            f"def input_{index}(+idx: U32) -> U32:\n"
            f"  U32.add({domain.start}, {offset})\n"
        )
        stride *= domain.size
    rendered = [_render(predicate, "idx") for predicate in predicates]
    bad_body = "0" if not rendered else rendered[0]
    for expression in rendered[1:]:
        bad_body = f"U32.or({bad_body}, {expression})"
    return f"""# Generated by BendSym. The cache key covers this complete source.
import Base

type Hit is Data:
  NoHit{{}}
  HitAt{{index: U32}}

def b2u(value: Bool) -> U32:
  match value:
    case True{{}}:
      1
    case False{{}}:
      0

def nz(value: U32) -> U32:
  b2u(U32.is_ne(value, 0))

{chr(10).join(input_defs)}
def bad(+idx: U32) -> U32:
  {bad_body}

def leaf.bad(+idx: U32, hit: Bool) -> Hit:
  match hit:
    case True{{}}:
      HitAt{{idx}}
    case False{{}}:
      NoHit{{}}

def leaf(+idx: U32, in_range: Bool) -> Hit:
  match in_range:
    case True{{}}:
      leaf.bad(idx, U32.is_ne(bad(idx), 0))
    case False{{}}:
      NoHit{{}}

def pick(left: Hit, right: Hit) -> Hit:
  match left:
    case HitAt{{index}}:
      HitAt{{index}}
    case NoHit{{}}:
      right

def search(depth: Nat, +base: U32, +active: U32) -> Hit:
  match depth:
    case 0n:
      leaf(base, U32.is_lt(base, active))
    case 1n++d:
      left right = search(d, base, active) search(d, U32.add(base, U32.shln(1, d)), active)
      pick(left, right)

def show(hit: Hit) -> String:
  match hit:
    case NoHit{{}}:
      "NONE"
    case HitAt{{index}}:
      U32.show(index)

def main() -> IO(Unit):
  IO.print(show(search{'!' if use_gpu else ''}({depth}n, 0, {candidates})))
"""


def _render(expr: Expr, index_name: str) -> str:
    if expr.op == "CONST":
        return str(expr.value)
    if expr.op == "INPUT":
        return f"input_{expr.value}({index_name})"
    left = _render(expr.left, index_name)
    if expr.op == "NOT":
        return f"U32.not({left})"
    if expr.op == "IS_ZERO":
        return f"b2u(U32.is_zero({left}))"
    if expr.op == "IS_NONZERO":
        return f"b2u(U32.is_ne({left}, 0))"
    right = _render(expr.right, index_name)
    function = {
        "ADD": "add", "SUB": "sub", "MUL": "mul", "AND": "and", "OR": "or", "XOR": "xor",
        "EQ": "is_eq", "ULT": "is_lt", "BOOL_AND": "and",
    }[expr.op]
    call = f"U32.{function}({left}, {right})"
    return f"b2u({call})" if expr.op in {"EQ", "ULT"} else call
